# Generated by Django 6.0.4 on 2026-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_amount_appointment_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('submitted', 'submitted'), ('verified', 'verified'), ('rejected', 'rejected')], default='unpaid', max_length=20),
        ),
    ]
