# Generated by Django 6.0.4 on 2026-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
