# Generated by Django 6.0.4 on 2026-05-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_doctor_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hidden_by_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hidden_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
