# Generated by Django 6.0.4 on 2026-05-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_hidden_by_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_deleted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_deleted',
        ),
    ]
