# Generated by Django 6.0.4 on 2026-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_appointment_doctor_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_amount',
            field=models.IntegerField(default=0),
        ),
    ]
