# Generated by Django 6.0.4 on 2026-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_image_doctor_phone_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_qr/'),
        ),
    ]
