# Generated by Django 6.0.4 on 2026-05-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedic', 'Orthopedic'), ('Dermatology', 'Dermatology'), ('Pediatric', 'Pediatric'), ('ENT', 'ENT'), ('Psychiatry', 'Psychiatry'), ('Gynecology', 'Gynecology'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=100),
        ),
    ]
