# Generated by Django 6.0.4 on 2026-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_available_days_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, help_text='Select available days', max_length=100, null=True),
        ),
    ]
